name: Repo Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install repo
        run: |
          sudo apt update
          sudo apt install -y git curl python3
          mkdir -p $HOME/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
          chmod +x $HOME/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Repo init test (shallow)
        run: |
          mkdir src
          cd src
          repo init -u https://github.com/OrangeFoxRecovery/Manifest.git -b fox_7.1 --depth=1
